-- Run once in Supabase SQL Editor after schema.sql

insert into gear_items (id, names_json, aliases_json, volume_liters, weight_grams, category, source_url, variants_json) values
('seed-0',  '{"en":"Sleeping bag (3-season)","de":"Schlafsack (3 Jahreszeiten)","ru":"Спальник (3 сезона)"}'::jsonb, '["sleeping bag 3 season","schlafsack","спальник"]'::jsonb, 6,    900,  'sleep',       null, '[{"sizeLabel":"Regular","volumeLiters":5.5,"weightGrams":820},{"sizeLabel":"Long","volumeLiters":6.5,"weightGrams":940}]'::jsonb),
('seed-1',  '{"en":"Sleeping bag (ultralight)","de":"Schlafsack (Ultraleicht)","ru":"Спальник ультралёгкий"}'::jsonb, '["ultralight sleeping bag","sleeping bag ultralight"]'::jsonb, 3.5, 500, 'sleep', null, '[{"sizeLabel":"Regular","volumeLiters":3.0,"weightGrams":470},{"sizeLabel":"Long","volumeLiters":3.8,"weightGrams":530}]'::jsonb),
('seed-2',  '{"en":"Inflatable sleeping pad","de":"Aufblasbare Isomatte","ru":"Надувной коврик"}'::jsonb, '["sleeping pad","isomatte","inflatable pad","коврик"]'::jsonb, 3, 500, 'sleep', null, '[{"sizeLabel":"Regular","volumeLiters":2.5,"weightGrams":430},{"sizeLabel":"Regular Wide","volumeLiters":3.0,"weightGrams":510},{"sizeLabel":"Large","volumeLiters":3.5,"weightGrams":560},{"sizeLabel":"Large Wide","volumeLiters":4.0,"weightGrams":620}]'::jsonb),
('seed-3',  '{"en":"Foam sleeping pad","de":"Schaum-Isomatte","ru":"Пенный коврик"}'::jsonb, '["foam pad","ccf pad","ridgerest"]'::jsonb, 4.5, 400, 'sleep', null, '[]'::jsonb),
('seed-4',  '{"en":"Bivy sack","de":"Biwaksack","ru":"Бивак"}'::jsonb, '["bivy","bivi","bivouac sack"]'::jsonb, 2, 350, 'shelter', null, '[]'::jsonb),
('seed-5',  '{"en":"Tent (1-person)","de":"Zelt (1 Person)","ru":"Палатка одноместная"}'::jsonb, '["tent 1p","solo tent","zelt 1p","палатка 1"]'::jsonb, 4, 1200, 'shelter', null, '[]'::jsonb),
('seed-6',  '{"en":"Tent (2-person)","de":"Zelt (2 Personen)","ru":"Палатка двухместная"}'::jsonb, '["tent 2p","two person tent","zelt 2p","палатка 2"]'::jsonb, 7, 1800, 'shelter', null, '[]'::jsonb),
('seed-7',  '{"en":"Tarp","de":"Plane","ru":"Тарп"}'::jsonb, '["tarp shelter","silnylon tarp"]'::jsonb, 1.5, 400, 'shelter', null, '[]'::jsonb),
('seed-8',  '{"en":"Rain jacket","de":"Regenjacke","ru":"Дождевик"}'::jsonb, '["rain coat","waterproof jacket","regenjacke","дождевик"]'::jsonb, 1.5, 350, 'clothing', null, '[]'::jsonb),
('seed-9',  '{"en":"Rain pants","de":"Regenhose","ru":"Дождевые штаны"}'::jsonb, '["waterproof pants","regenhose"]'::jsonb, 0.8, 250, 'clothing', null, '[]'::jsonb),
('seed-10', '{"en":"Down jacket","de":"Daunenjacke","ru":"Пуховик"}'::jsonb, '["puffy jacket","down puffy","daunenjacke","пуховик"]'::jsonb, 3, 400, 'clothing', null, '[]'::jsonb),
('seed-11', '{"en":"Cycling jersey (x3)","de":"Radtrikot (x3)","ru":"Веломайки (x3)"}'::jsonb, '["cycling jerseys","bike jersey"]'::jsonb, 1.5, 300, 'clothing', null, '[]'::jsonb),
('seed-12', '{"en":"Cycling bib shorts (x2)","de":"Radhose (x2)","ru":"Велошорты (x2)"}'::jsonb, '["bib shorts","cycling shorts","radhose"]'::jsonb, 1, 400, 'clothing', null, '[]'::jsonb),
('seed-13', '{"en":"Gas canister 230g","de":"Gaskartusche 230g","ru":"Газовый баллон 230г"}'::jsonb, '["gas canister","fuel canister","isobutane"]'::jsonb, 0.6, 390, 'cooking', null, '[]'::jsonb),
('seed-14', '{"en":"Camp stove","de":"Campingkocher","ru":"Туристическая горелка"}'::jsonb, '["camping stove","backpacking stove","kocher","горелка"]'::jsonb, 0.5, 200, 'cooking', null, '[]'::jsonb),
('seed-15', '{"en":"Titanium pot 0.9L","de":"Titan-Topf 0,9L","ru":"Титановый котелок 0.9Л"}'::jsonb, '["titanium pot","camp pot","cooking pot","котелок"]'::jsonb, 1, 130, 'cooking', null, '[]'::jsonb),
('seed-16', '{"en":"Bike multi-tool","de":"Fahrrad-Multitool","ru":"Мультитул для велосипеда"}'::jsonb, '["multitool","multi tool","bike tool","мультитул"]'::jsonb, 0.3, 200, 'tools', null, '[]'::jsonb),
('seed-17', '{"en":"Spare tubes (x2)","de":"Ersatzschläuche (x2)","ru":"Запасные камеры (x2)"}'::jsonb, '["inner tubes","spare tube","запасные камеры","камеры"]'::jsonb, 0.5, 250, 'tools', null, '[]'::jsonb),
('seed-18', '{"en":"Tire levers + patch kit","de":"Reifenheber + Flickzeug","ru":"Монтажки + латки"}'::jsonb, '["patch kit","tire lever","tyre lever","монтажки"]'::jsonb, 0.2, 80, 'tools', null, '[]'::jsonb),
('seed-19', '{"en":"Mini pump","de":"Minipumpe","ru":"Мининасос"}'::jsonb, '["bike pump","frame pump","насос"]'::jsonb, 0.3, 120, 'tools', null, '[]'::jsonb),
('seed-20', '{"en":"First aid kit","de":"Erste-Hilfe-Set","ru":"Аптечка"}'::jsonb, '["first aid","medical kit","аптечка"]'::jsonb, 0.5, 200, 'hygiene', null, '[]'::jsonb),
('seed-21', '{"en":"Toiletry bag","de":"Kulturbeutel","ru":"Косметичка"}'::jsonb, '["toiletries","wash bag","kulturbeutel","косметичка"]'::jsonb, 1.5, 500, 'hygiene', null, '[]'::jsonb),
('seed-22', '{"en":"Smartphone","de":"Smartphone","ru":"Смартфон"}'::jsonb, '["phone","handy","телефон","iphone","android"]'::jsonb, 0.2, 200, 'electronics', null, '[]'::jsonb),
('seed-23', '{"en":"Power bank 20000mAh","de":"Powerbank 20000mAh","ru":"Павербанк 20000мАч"}'::jsonb, '["powerbank","power bank","portable charger","павербанк"]'::jsonb, 0.8, 450, 'electronics', null, '[]'::jsonb),
('seed-24', '{"en":"USB charger + cables","de":"USB-Ladegerät + Kabel","ru":"Зарядник + кабели"}'::jsonb, '["charger","usb cable","зарядник"]'::jsonb, 0.3, 150, 'electronics', null, '[]'::jsonb),
('seed-25', '{"en":"Bike computer / GPS","de":"Fahrradcomputer / GPS","ru":"Велокомпьютер / GPS"}'::jsonb, '["garmin","wahoo","bike gps","велокомпьютер"]'::jsonb, 0.2, 100, 'navigation', null, '[]'::jsonb),
('seed-26', '{"en":"Water filter","de":"Wasserfilter","ru":"Фильтр для воды"}'::jsonb, '["filter","sawyer","waterfilter","фильтр"]'::jsonb, 0.3, 100, 'water', null, '[]'::jsonb),
('seed-27', '{"en":"Water bottle 750ml","de":"Trinkflasche 750ml","ru":"Бутылка 750мл"}'::jsonb, '["water bottle","trinkflasche","бутылка с водой"]'::jsonb, 0.75, 100, 'water', null, '[]'::jsonb),
('seed-28', '{"en":"Hydration bladder 2L","de":"Trinkblase 2L","ru":"Гидратор 2Л"}'::jsonb, '["hydration bladder","camelback","platypus","гидратор"]'::jsonb, 2, 200, 'water', null, '[]'::jsonb),
('seed-29', '{"en":"Ortlieb Seat-Pack S (11L)","de":"Ortlieb Seat-Pack S (11L)","ru":"Ortlieb Seat-Pack S (11L)"}'::jsonb, '["ortlieb seat-pack s","seat-pack s"]'::jsonb, 11, 390, 'other', 'https://www.ortlieb.com/en/seat-pack', '[]'::jsonb),
('seed-30', '{"en":"Ortlieb Seat-Pack QR (13L)","de":"Ortlieb Seat-Pack QR (13L)","ru":"Ortlieb Seat-Pack QR (13L)"}'::jsonb, '["ortlieb seat-pack qr","seat-pack qr"]'::jsonb, 13, 430, 'other', 'https://www.ortlieb.com/en/seat-pack-qr', '[]'::jsonb),
('seed-31', '{"en":"Apidura Backcountry Handlebar Pack (9L)","de":"Apidura Backcountry Handlebar Pack (9L)","ru":"Apidura Backcountry Handlebar Pack (9L)"}'::jsonb, '["apidura handlebar","apidura backcountry handlebar"]'::jsonb, 9, 330, 'other', 'https://www.apidura.com', '[]'::jsonb)
on conflict (id) do nothing;
