#!/usr/bin/env npx tsx
/**
 * Fetch og:image (and twitter:image fallback) for every bag in the
 * catalogue, then emit an SQL file with UPDATE statements that you
 * paste into the Supabase SQL Editor.
 *
 * Usage:
 *   npx tsx scripts/fetch-bag-images.ts
 *   → writes docs/bag-images.sql
 *   → paste into Supabase SQL Editor
 *
 * Why this approach (not a live API endpoint):
 * - Manufacturer pages don't change often; one-shot is enough
 * - Bag_products RLS only allows anon SELECT; writes need elevated
 *   access. SQL Editor runs as service-role, bypasses RLS cleanly.
 * - Keeps Vercel runtime light.
 *
 * Honest constraints:
 * - Skips bags that already have image_url set (idempotent)
 * - Some manufacturer pages block scrapers (403); those stay NULL
 * - og:image tags can serve large hero shots (1200×630); fine for
 *   our 36–48px thumbnails because next/image runs unoptimized
 */
import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'fs';
import { join } from 'path';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
if (!url || !key) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY in env');
  process.exit(1);
}
const supabase = createClient(url, key);

interface Bag {
  id: string;
  brand: string;
  model: string;
  source_url: string | null;
  image_url: string | null;
}

function extractOgImage(html: string, sourceUrl: string): string | null {
  // Try og:image first, then twitter:image
  const patterns = [
    /<meta\s+(?:[^>]*?\s+)?property=["']og:image["'][^>]*?content=["']([^"']+)["']/i,
    /<meta\s+(?:[^>]*?\s+)?content=["']([^"']+)["'][^>]*?property=["']og:image["']/i,
    /<meta\s+(?:[^>]*?\s+)?name=["']twitter:image["'][^>]*?content=["']([^"']+)["']/i,
    /<meta\s+(?:[^>]*?\s+)?content=["']([^"']+)["'][^>]*?name=["']twitter:image["']/i,
  ];
  for (const p of patterns) {
    const m = html.match(p);
    if (m && m[1]) {
      // Normalise to absolute URL
      try {
        return new URL(m[1], sourceUrl).toString();
      } catch {
        continue;
      }
    }
  }
  return null;
}

async function fetchImage(bag: Bag): Promise<string | null> {
  if (!bag.source_url) return null;
  try {
    const res = await fetch(bag.source_url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; Veloadout/1.0; +https://veloadout.com)',
        'Accept': 'text/html,application/xhtml+xml',
      },
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) {
      console.warn(`  ✗ ${bag.id}: HTTP ${res.status}`);
      return null;
    }
    const html = await res.text();
    const img = extractOgImage(html, bag.source_url);
    if (img && /^https?:\/\//.test(img)) {
      return img;
    }
    return null;
  } catch (err) {
    console.warn(`  ✗ ${bag.id}: ${(err as Error).message}`);
    return null;
  }
}

async function run() {
  console.log('Loading bags from Supabase…');
  const { data, error } = await supabase
    .from('bag_products')
    .select('id, brand, model, source_url, image_url')
    .order('id');
  if (error) {
    console.error('Failed to load bags:', error.message);
    process.exit(1);
  }
  const bags = (data ?? []) as Bag[];
  const todo = bags.filter(b => !b.image_url && b.source_url);
  console.log(`${bags.length} bags total, ${todo.length} need images`);

  const updates: string[] = [];
  let ok = 0, fail = 0;
  for (let i = 0; i < todo.length; i++) {
    const bag = todo[i];
    process.stdout.write(`[${i + 1}/${todo.length}] ${bag.id} → `);
    const img = await fetchImage(bag);
    if (img) {
      ok++;
      console.log(img.slice(0, 60) + (img.length > 60 ? '…' : ''));
      const safeImg = img.replace(/'/g, "''");
      const safeId  = bag.id.replace(/'/g, "''");
      updates.push(`UPDATE bag_products SET image_url = '${safeImg}', updated_at = now() WHERE id = '${safeId}';`);
    } else {
      fail++;
      console.log('(none)');
    }
    // Be polite — small delay between requests
    await new Promise(r => setTimeout(r, 250));
  }

  const outPath = join(process.cwd(), 'docs', 'bag-images.sql');
  const header = `-- Auto-generated by scripts/fetch-bag-images.ts at ${new Date().toISOString()}\n-- ${ok} bags resolved, ${fail} failed.\n-- Paste into Supabase SQL Editor.\n\nbegin;\n\n`;
  const footer = '\ncommit;\n';
  writeFileSync(outPath, header + updates.join('\n') + footer);
  console.log(`\nWrote ${updates.length} UPDATE statements → ${outPath}`);
  console.log(`Success: ${ok}, failed: ${fail}, already-set: ${bags.length - todo.length}`);
}

run();
