-- Auto-generated by scripts/fetch-bag-images.ts at 2026-05-18T21:30:10.160Z
-- 21 bags resolved, 32 failed.
-- Sources: {"meta":21}
-- Paste into Supabase SQL Editor.

begin;

UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2025/09/apidura-backcountry-frame-pack-2l-on-bike-1.jpg', updated_at = now() WHERE id = 'apidura-backcountry-frame-2';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2025/09/apidura-backcountry-frame-pack-2l-on-bike-1.jpg', updated_at = now() WHERE id = 'apidura-backcountry-frame-4';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2018/07/apidura-backcountry-full-frame-pack-4l-on-bike-1-2.jpg', updated_at = now() WHERE id = 'apidura-backcountry-frame-6';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2018/07/apidura-backcountry-saddle-pack-6l-on-bike-1-2.jpg', updated_at = now() WHERE id = 'apidura-backcountry-saddle-11';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2018/07/apidura-backcountry-saddle-pack-6l-on-bike-1-2.jpg', updated_at = now() WHERE id = 'apidura-backcountry-saddle-14';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2018/07/apidura-backcountry-saddle-pack-6l-on-bike-1-2.jpg', updated_at = now() WHERE id = 'apidura-backcountry-saddle-17';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2018/07/apidura-backcountry-saddle-pack-6l-on-bike-1-2.jpg', updated_at = now() WHERE id = 'apidura-backcountry-saddle-6';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2024/05/apidura-expedition-cargo-cage-pack-1.3l-on-bike-1.jpg', updated_at = now() WHERE id = 'apidura-expedition-fork-7';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2024/05/apidura-expedition-cargo-cage-pack-1.3l-on-bike-1.jpg', updated_at = now() WHERE id = 'apidura-expedition-fork-7-5';
UPDATE bag_products SET image_url = 'https://medias.apidura.com/sHRQ6jzh/2024/05/apidura-expedition-cargo-cage-pack-1.3l-on-bike-1.jpg', updated_at = now() WHERE id = 'apidura-expedition-fork-9';
UPDATE bag_products SET image_url = 'https://restrap.com/cdn/shop/products/Bar-Pack-Restrap-Black_1024x1024.jpg?v=1669974040', updated_at = now() WHERE id = 'restrap-bar-pack-14';
UPDATE bag_products SET image_url = 'https://restrap.com/cdn/shop/products/Bar-Pack-Restrap-Black_1024x1024.jpg?v=1669974040', updated_at = now() WHERE id = 'restrap-bar-pack-17';
UPDATE bag_products SET image_url = 'https://restrap.com/cdn/shop/products/00_Fork_Bag_1024x1024.jpg?v=1600789326', updated_at = now() WHERE id = 'restrap-fork-bag-4';
UPDATE bag_products SET image_url = 'https://restrap.com/cdn/shop/products/00_Fork_Bag_1024x1024.jpg?v=1600789326', updated_at = now() WHERE id = 'restrap-fork-bag-6';
UPDATE bag_products SET image_url = 'https://media.tailfin.cc/app/uploads/2026/01/12151731/700X500-CARGOPACK-NEW-BRANDING-FEATURED-IMAGE.jpg', updated_at = now() WHERE id = 'tailfin-aeropack-22';
UPDATE bag_products SET image_url = 'https://www.topeak.com/storage/app/mediahttps://www.topeak.com/storage/app/media/index/meta-image.jpg', updated_at = now() WHERE id = 'topeak-backloader-10';
UPDATE bag_products SET image_url = 'https://www.topeak.com/storage/app/mediahttps://www.topeak.com/storage/app/media/index/meta-image.jpg', updated_at = now() WHERE id = 'topeak-backloader-15';
UPDATE bag_products SET image_url = 'https://www.topeak.com/storage/app/mediahttps://www.topeak.com/storage/app/media/index/meta-image.jpg', updated_at = now() WHERE id = 'topeak-frontloader-8';
UPDATE bag_products SET image_url = 'https://www.topeak.com/storage/app/mediahttps://www.topeak.com/storage/app/media/index/meta-image.jpg', updated_at = now() WHERE id = 'topeak-midloader-4-5';
UPDATE bag_products SET image_url = 'https://www.topeak.com/storage/app/mediahttps://www.topeak.com/storage/app/media/index/meta-image.jpg', updated_at = now() WHERE id = 'topeak-midloader-6';
UPDATE bag_products SET image_url = 'https://www.topeak.com/storage/app/mediahttps://www.topeak.com/storage/app/media/index/meta-image.jpg', updated_at = now() WHERE id = 'topeak-versacage';
commit;
